version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install awscli --upgrade --user
      # - aws codeartifact login --tool pip --domain my_domain --domain-owner 111122223333 --repository my_repo
      - cd app/
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
  build:
    commands:
      - python -m pytest

reports:
  pytest_reports:
    files:
      - report.xml
    base-directory: reports
    file-format: JUNITXML

